/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : BookingId,
  'service' : MakeupService,
  'customerName' : string,
  'status' : BookingStatus,
  'owner' : [] | [Principal],
  'date' : string,
  'email' : string,
  'phone' : string,
  'timeSlot' : Slot,
}
export type BookingId = bigint;
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface MakeupService {
  'id' : ServiceId,
  'duration' : bigint,
  'name' : string,
  'description' : string,
  'price' : number,
}
export type ServiceId = bigint;
export type Slot = string;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<
    [ServiceId, string, string, string, string, Slot],
    BookingId
  >,
  'cancelMyBooking' : ActorMethod<[BookingId], undefined>,
  'createService' : ActorMethod<[string, string, bigint, number], ServiceId>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllServices' : ActorMethod<[], Array<MakeupService>>,
  'getAvailableTimeSlots' : ActorMethod<[ServiceId, string], Array<Slot>>,
  'getBooking' : ActorMethod<[BookingId], [] | [Booking]>,
  'getBookingsForDate' : ActorMethod<[ServiceId, string], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isTimeSlotAvailable' : ActorMethod<[ServiceId, string, Slot], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBookingStatus' : ActorMethod<[BookingId, BookingStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];