/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceId = IDL.Nat;
export const Slot = IDL.Text;
export const BookingId = IDL.Nat;
export const MakeupService = IDL.Record({
  'id' : ServiceId,
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : BookingId,
  'service' : MakeupService,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'owner' : IDL.Opt(IDL.Principal),
  'date' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'timeSlot' : Slot,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func(
      [ServiceId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Slot],
      [BookingId],
      [],
    ),
  'cancelMyBooking' : IDL.Func([BookingId], [], []),
  'createService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
      [ServiceId],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(MakeupService)], ['query']),
  'getAvailableTimeSlots' : IDL.Func(
      [ServiceId, IDL.Text],
      [IDL.Vec(Slot)],
      ['query'],
    ),
  'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
  'getBookingsForDate' : IDL.Func(
      [ServiceId, IDL.Text],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isTimeSlotAvailable' : IDL.Func(
      [ServiceId, IDL.Text, Slot],
      [IDL.Bool],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBookingStatus' : IDL.Func([BookingId, BookingStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceId = IDL.Nat;
  const Slot = IDL.Text;
  const BookingId = IDL.Nat;
  const MakeupService = IDL.Record({
    'id' : ServiceId,
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : BookingId,
    'service' : MakeupService,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'owner' : IDL.Opt(IDL.Principal),
    'date' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'timeSlot' : Slot,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func(
        [ServiceId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Slot],
        [BookingId],
        [],
      ),
    'cancelMyBooking' : IDL.Func([BookingId], [], []),
    'createService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
        [ServiceId],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(MakeupService)], ['query']),
    'getAvailableTimeSlots' : IDL.Func(
        [ServiceId, IDL.Text],
        [IDL.Vec(Slot)],
        ['query'],
      ),
    'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
    'getBookingsForDate' : IDL.Func(
        [ServiceId, IDL.Text],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isTimeSlotAvailable' : IDL.Func(
        [ServiceId, IDL.Text, Slot],
        [IDL.Bool],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBookingStatus' : IDL.Func([BookingId, BookingStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };