/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : BookingId,
  'service' : string,
  'customerName' : string,
  'status' : BookingStatus,
  'customerPhone' : string,
  'appointmentDate' : Time,
  'appointmentTime' : string,
  'timestamp' : Time,
  'customerEmail' : string,
}
export type BookingId = bigint;
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface CompanyService {
  'id' : bigint,
  'duration' : bigint,
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export interface Lead {
  'id' : LeadId,
  'customerName' : string,
  'status' : LeadStatus,
  'email' : string,
  'timestamp' : Time,
  'category' : [] | [string],
  'phone' : string,
}
export type LeadId = bigint;
export type LeadStatus = { 'new' : null } |
  { 'closed' : null } |
  { 'contacted' : null } |
  { 'converted' : null };
export interface ServiceCategory {
  'id' : string,
  'icon' : string,
  'name' : string,
  'color' : string,
  'services' : Array<CompanyService>,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPrincipalNameMapping' : ActorMethod<[Principal, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBookingEntry' : ActorMethod<
    [string, Time, string, string, string, string, BookingStatus],
    BookingId
  >,
  'createLead' : ActorMethod<[[] | [string], string, string, string], LeadId>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllBookingsByStatus' : ActorMethod<[BookingStatus], Array<Booking>>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getBooking' : ActorMethod<[BookingId], [] | [Booking]>,
  'getBookingsByDateRange' : ActorMethod<[Time, Time], Array<Booking>>,
  'getBookingsByService' : ActorMethod<[string], Array<Booking>>,
  'getCallerName' : ActorMethod<[], [] | [string]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLead' : ActorMethod<[LeadId], [] | [Lead]>,
  'getLeadsByStatus' : ActorMethod<[LeadStatus], Array<Lead>>,
  'getPrincipalByName' : ActorMethod<[string], [] | [Principal]>,
  'getServices' : ActorMethod<[], Array<ServiceCategory>>,
  'getUserByPrincipal' : ActorMethod<[Principal], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isTimeSlotAvailableEntry' : ActorMethod<[string, Time, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBookingStatusEntry' : ActorMethod<
    [BookingId, BookingStatus],
    undefined
  >,
  'updateLeadStatus' : ActorMethod<[LeadId, LeadStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];