/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const BookingId = IDL.Nat;
export const LeadId = IDL.Nat;
export const Booking = IDL.Record({
  'id' : BookingId,
  'service' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'customerPhone' : IDL.Text,
  'appointmentDate' : Time,
  'appointmentTime' : IDL.Text,
  'timestamp' : Time,
  'customerEmail' : IDL.Text,
});
export const LeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'closed' : IDL.Null,
  'contacted' : IDL.Null,
  'converted' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : LeadId,
  'customerName' : IDL.Text,
  'status' : LeadStatus,
  'email' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const CompanyService = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const ServiceCategory = IDL.Record({
  'id' : IDL.Text,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'services' : IDL.Vec(CompanyService),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPrincipalNameMapping' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBookingEntry' : IDL.Func(
      [IDL.Text, Time, IDL.Text, IDL.Text, IDL.Text, IDL.Text, BookingStatus],
      [BookingId],
      [],
    ),
  'createLead' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Text],
      [LeadId],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllBookingsByStatus' : IDL.Func(
      [BookingStatus],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
  'getBookingsByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookingsByService' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getCallerName' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLead' : IDL.Func([LeadId], [IDL.Opt(Lead)], ['query']),
  'getLeadsByStatus' : IDL.Func([LeadStatus], [IDL.Vec(Lead)], ['query']),
  'getPrincipalByName' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'getServices' : IDL.Func([], [IDL.Vec(ServiceCategory)], ['query']),
  'getUserByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isTimeSlotAvailableEntry' : IDL.Func(
      [IDL.Text, Time, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBookingStatusEntry' : IDL.Func([BookingId, BookingStatus], [], []),
  'updateLeadStatus' : IDL.Func([LeadId, LeadStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const BookingId = IDL.Nat;
  const LeadId = IDL.Nat;
  const Booking = IDL.Record({
    'id' : BookingId,
    'service' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'customerPhone' : IDL.Text,
    'appointmentDate' : Time,
    'appointmentTime' : IDL.Text,
    'timestamp' : Time,
    'customerEmail' : IDL.Text,
  });
  const LeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'closed' : IDL.Null,
    'contacted' : IDL.Null,
    'converted' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : LeadId,
    'customerName' : IDL.Text,
    'status' : LeadStatus,
    'email' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CompanyService = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ServiceCategory = IDL.Record({
    'id' : IDL.Text,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'services' : IDL.Vec(CompanyService),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPrincipalNameMapping' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBookingEntry' : IDL.Func(
        [IDL.Text, Time, IDL.Text, IDL.Text, IDL.Text, IDL.Text, BookingStatus],
        [BookingId],
        [],
      ),
    'createLead' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Text],
        [LeadId],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllBookingsByStatus' : IDL.Func(
        [BookingStatus],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
    'getBookingsByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByService' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerName' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLead' : IDL.Func([LeadId], [IDL.Opt(Lead)], ['query']),
    'getLeadsByStatus' : IDL.Func([LeadStatus], [IDL.Vec(Lead)], ['query']),
    'getPrincipalByName' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getServices' : IDL.Func([], [IDL.Vec(ServiceCategory)], ['query']),
    'getUserByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isTimeSlotAvailableEntry' : IDL.Func(
        [IDL.Text, Time, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBookingStatusEntry' : IDL.Func([BookingId, BookingStatus], [], []),
    'updateLeadStatus' : IDL.Func([LeadId, LeadStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };